// This file is machine-generated - edit with care!

'use server';

/**
 * @fileOverview An AI agent that generates a professional profile for an instructor.
 *
 * - generateInstructorProfile - A function that handles the profile generation process.
 * - GenerateInstructorProfileInput - The input type for the generateInstructorProfile function.
 * - GenerateInstructorProfileOutput - The return type for the generateInstructorProfile function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateInstructorProfileInputSchema = z.object({
  prompt: z.string().describe('A basic prompt describing the instructor and their expertise.'),
});
export type GenerateInstructorProfileInput = z.infer<
  typeof GenerateInstructorProfileInputSchema
>;

const GenerateInstructorProfileOutputSchema = z.object({
  profileDraft: z
    .string()
    .describe('A draft of the professional profile generated by the AI.'),
});
export type GenerateInstructorProfileOutput = z.infer<
  typeof GenerateInstructorProfileOutputSchema
>;

export async function generateInstructorProfile(
  input: GenerateInstructorProfileInput
): Promise<GenerateInstructorProfileOutput> {
  return generateInstructorProfileFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateInstructorProfilePrompt',
  input: {schema: GenerateInstructorProfileInputSchema},
  output: {schema: GenerateInstructorProfileOutputSchema},
  prompt: `You are a professional profile writer. Generate a compelling professional profile based on the following information: {{{prompt}}}. The profile should be trustworthy and highlight the instructor's expertise to attract more students. Use different formulations and layouts to make it stand out. Ask for the instructor's permission before publishing.`,
});

const generateInstructorProfileFlow = ai.defineFlow(
  {
    name: 'generateInstructorProfileFlow',
    inputSchema: GenerateInstructorProfileInputSchema,
    outputSchema: GenerateInstructorProfileOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
